config/routes.rb
Meifang::Application.routes.draw do
  root to: 'static_pages#home'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/map', to: 'static_pages#map', via: 'get'
  match '/master_new', to: 'static_pages#master_new', via: 'get'
  match '/register', to: 'static_pages#register', via: 'get'
  devise_for :users

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  resources :categories
  mount Ckeditor::Engine => '/ckeditor'

  resources :information
  resources :new_homes
  resources :group_buyings
  resources :intention_to_registers
  resources :information_sharings
  resources :characters
  resources :about

  match '/intention_to_registers_new_homes', to: 'static_pages#get_new_homes', via: 'get'

  require 'sidekiq/web'
  require 'sidetiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :new_home
  belongs_to :album_class

  mount_uploader :url, AlubmUploader
end

app/models/album_class.rb
class AlbumClass < ActiveRecord::Base
  has_many :albums, dependent: :destroy
end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
  belongs_to :new_home

  mount_uploader :apartment_thumb, ApartmentUploader
end

app/models/area.rb
class Area < ActiveRecord::Base
  has_many :new_homes
end

app/models/area_range.rb
class AreaRange < ActiveRecord::Base
  has_many :new_homes
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :information, dependent: :destroy
  validates :name, presence: true

  has_ancestry
end

app/models/character.rb
class Character < ActiveRecord::Base
  mount_uploader :character_thumb, CharacterThumbUploader
end

app/models/developers.rb
class Developers < ActiveRecord::Base
  has_many :new_homes, dependent: :destroy
end

app/models/dummy_data.rb
class DummyData < ActiveRecord::Base
  belongs_to :new_home
end

app/models/group_buying.rb
class GroupBuying < ActiveRecord::Base
  belongs_to :new_home
end

app/models/information.rb
class Information < ActiveRecord::Base
  belongs_to :category
  belongs_to :new_home
  belongs_to :information_type

  validates :category, presence: true
  validates :title, presence: true
  validates :content, presence: true
  validates :keywords, length: { maximum: 100 }
  validates :description, length: { maximum: 200 }

  mount_uploader :information_thumb, InformationThumbUploader

  searchable do
    integer :information_type_id
    integer :category_id
    text :title, :boost => 5
    text :description
    text :content
    time :created_at
  end
end

app/models/information_type.rb
class InformationType < ActiveRecord::Base
  has_many :information
end

app/models/new_home.rb
class NewHome < ActiveRecord::Base
  belongs_to :area
  belongs_to :developers
  belongs_to :status
  belongs_to :section
  belongs_to :property_type
  belongs_to :construction_category
  belongs_to :area_range
  belongs_to :project_features

  has_many :information
  has_many :information_estate_openeds, dependent: :destroy

  has_many :albums, dependent: :destroy
  accepts_nested_attributes_for :albums, :allow_destroy => true

  has_many :group_buyings, dependent: :destroy
  has_many :intention_to_registers, dependent: :destroy

  has_many :apartments, dependent: :destroy
  accepts_nested_attributes_for :apartments, :allow_destroy => true

  VALID_NUMBER_REGEX = /[\d]/
  validates :name, presence: true
  validates :price, format: { with: VALID_NUMBER_REGEX }
  validates :area, presence:true
  validates :developers, presence:true
  validates :status, presence:true

  mount_uploader :new_home_thumb, NewHomeThumbUploader

  searchable do
    text :name, :boost => 5
    integer :area_id
    integer :section_id
    integer :area_range_id
    integer :property_type_id
    integer :price
    integer :status_id
    text :content
    time :created_at
  end
end

app/models/property_type.rb
class PropertyType < ActiveRecord::Base
  has_many :new_homes
end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :new_homes
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :new_homes
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable #添加该项，注册后要邮箱验证
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  respond_to :html, :xml, :json

  def home
    @areas = Area.all
    @sections = Section.all
    @intention_to_register = IntentionToRegister.new

    # 首页全站新闻
    @lpsd = JSON.parse(open(URI.escape("http://www.xinwowang.com/api/information?information_type_id=2")).read)
    @lpyh = JSON.parse(open(URI.escape("http://www.xinwowang.com/api/information?information_type_id=3")).read)
    @lppc = JSON.parse(open(URI.escape("http://www.xinwowang.com/api/information?information_type_id=4")).read)
    @fsbg = JSON.parse(open(URI.escape("http://www.xinwowang.com/api/information?information_type_id=13")).read)
  end

  def help

  end

  def map
    @map_keyword = params[:map_keyword]
    unless @map_keyword.blank?
      @new_homes = NewHome.where("name LIKE ? AND map_address IS NOT NULL", '%' + @map_keyword + '%')
    else
      @new_homes = NewHome.where("map_address IS NOT NULL")
    end
  end

  def get_new_homes
    options = ""
    area_id = params[:area_id]
    if area_id.blank?
      data_for_select = NewHome.all
    else
      data_for_select = NewHome.where(:area_id => area_id).all
    end
    data_for_select.each do |s|
      options << "<option value=#{s.id}>#{s.name}</option>"
    end
    render :text => options
    # render :json => @data_for_select.map{|c| [c.id, c.name]}
  end

  def master_new
    @information = JSON.parse(open(URI.escape("http://www.xinwowang.com/api/information?information_type_id=#{params["id"]}")).read)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/help.html.haml
- provide(:title, 'Help')
%h1
  StaticPages#help
%p
  Find me in app/views/static_pages/help.help.erb

app/views/static_pages/map.html.haml
%script{src: "http://api.map.baidu.com/api?v=2.0&ak=NXagVEyXSs6AmnrCNXl7pKHo", type: "text/javascript"}
= form_tag '', :method => :get, :class => "form-inline", :role => "form" do
  .selectItemhidden#selectItem
    .selectItemcont#selectItemCount
      #selectSub
        #r-result{ :style => "width: 20%; float: right;" }
          #search{ :style => "margin-top: 10px; margin-left: 10px;" }
            搜索
            = text_field_tag :map_keyword, "", :class => "form-control", :id => "map_keyword", :style => "width: 100px", :size => "20",:placeholder => "请输入楼盘"
            %button.btn.btn-danger{ type: "submit", style: "height: 28px; width: 58px", onclick: "MblogDotccMap(document.getElementById('map_keyword').value)" }
              搜索
          #results_info{ :style => "margin-top: 10px; margin-left: 10px;" }
        #l-map{ :style => "height: 650px; width: 80%; float: left;" }
.clearfix
:javascript
  var map = new BMap.Map("l-map");
  var point = new BMap.Point(117.676205,24.517065);

  map.centerAndZoom(point, 13);
  // 控件

  map.addControl(new BMap.NavigationControl());
  map.addControl(new BMap.NavigationControl({anchor: BMAP_ANCHOR_BOTTOM_LEFT, type: BMAP_NAVIGATION_CONTROL_PAN}));  //左下角，仅包含平移按钮

  map.addControl(new BMap.ScaleControl());

  map.addControl(new BMap.OverviewMapControl());
  map.addControl(new BMap.OverviewMapControl({isOpen:true, anchor: BMAP_ANCHOR_BOTTOM_RIGHT}));   //右上角，打开

  map.addControl(new BMap.MapTypeControl({mapTypes: [BMAP_NORMAL_MAP,BMAP_HYBRID_MAP]}));     //2D图，卫星图




  function MblogDotccMap(keyword) {
    var local = new BMap.LocalSearch(map, {renderOptions: {map: map, panel: "results_info"}});
    map.panBy(point);
    local.search(keyword);
    local.getResults();
  }

  // 加载值到输入框
  map.addEventListener('click', function(e){ document.getElementById('new_home_map_address').value = e.point.lng + ', ' + e.point.lat;});

  // 复杂的自定义覆盖物
  function ComplexCustomOverlay(point, text, price, project_address, show, tel){
    this._point = point;
    this._text = text;
    this._price = price;
    this._project_address = project_address;
    this._show = show;
    this._tel = tel;
  }
  ComplexCustomOverlay.prototype = new BMap.Overlay();
  ComplexCustomOverlay.prototype.initialize = function(map){
    this._map = map;
    var div = this._div = document.createElement("div");
    div.style.position = "absolute";
    div.style.zIndex = BMap.Overlay.getZIndex(this._point.lat);
    div.style.backgroundColor = "#EE5D5B";
    div.style.border = "1px solid #BC3B3A";
    div.style.color = "white";
    div.style.height = "18px";
    div.style.padding = "2px";
    div.style.lineHeight = "18px";
    div.style.whiteSpace = "nowrap";
    div.style.MozUserSelect = "none";
    div.style.fontSize = "12px"
    var span = this._span = document.createElement("span");
    div.appendChild(span);
    span.appendChild(document.createTextNode(this._text));
    var that = this;

    var arrow = this._arrow = document.createElement("div");
    arrow.style.background = "url(http://map.baidu.com/fwmap/upload/r/map/fwmap/static/house/images/label.png) no-repeat";
    arrow.style.position = "absolute";
    arrow.style.width = "11px";
    arrow.style.height = "10px";
    arrow.style.top = "22px";
    arrow.style.left = "10px";
    arrow.style.overflow = "hidden";
    div.appendChild(arrow);

    div.onmouseover = function(){
      // this.style.backgroundColor = "#6BADCA";
      // this.style.borderColor = "#0000ff";
      // this.getElementsByTagName("span")[0].innerHTML = that._overText;
      // arrow.style.backgroundPosition = "0px -20px";

      var opts = {
        width : 350,     // 信息窗口宽度
        // height: 100,     // 信息窗口高度
        title : "<b>"+that._text+"</b>"  // 信息窗口标题
      }
      var content = "<table class='table'>\
                       <tr>\
                         <td>\
                           <div class='pull-left'>\
                             均价：<span style='color:#ff7d00; font-size:16px''><strong>"+that._price+"</strong></span>元/㎡\
                             <br>\
                             楼盘地址："+that._project_address+"\
                             <br>\
                             <a href='/new_homes/"+that._show+"' target='_blank'>查看楼盘详情&gt;&gt;</a>\
                           </div>\
                           <div class='pull-right'>\
                             <img src='/uploads/new_home/new_home_thumb/"+that._show+"/small_thumb.jpg'>\
                           </div>\
                         </td>\
                       </tr>\
                       <tr>\
                         <td>\
                           如果您对楼盘有兴趣&nbsp;可拨打以下电话咨询\
                           <br>\
                           <h4 style='color:#007acc'>"+that._tel+"</h4>\
                         </td>\
                       </tr>\
                     </table>\
                     ";
      var infoWindow = new BMap.InfoWindow(content, opts);  // 创建信息窗口对象
      map.openInfoWindow(infoWindow, that._point);      // 打开信息窗口

    }

    div.onmouseout = function(){
      this.style.backgroundColor = "#EE5D5B";
      this.style.borderColor = "#BC3B3A";
      this.getElementsByTagName("span")[0].innerHTML = that._text;
      arrow.style.backgroundPosition = "0px 0px";
    }

    map.getPanes().labelPane.appendChild(div);

    return div;
  }
  ComplexCustomOverlay.prototype.draw = function(){
    var map = this._map;
    var pixel = map.pointToOverlayPixel(this._point);
    this._div.style.left = pixel.x - parseInt(this._arrow.style.left) + "px";
    this._div.style.top  = pixel.y - 30 + "px";
  }

  var map_keyword = "#{@map_keyword}";

  var new_homes = #{@new_homes.to_json};

  for(var item in new_homes){
    var map_address = new_homes[item].map_address.split(",");
    var name = new_homes[item].name;
    var price = new_homes[item].price;
    var project_address = new_homes[item].project_address;
    var show = new_homes[item].id;
    var tel = new_homes[item].tel;
    var myCompOverlay = new ComplexCustomOverlay(new BMap.Point(map_address[0], map_address[1]), name, price, project_address, show, tel);
    map.addOverlay(myCompOverlay);
  }

app/views/static_pages/master_new.html.haml
-provide(:title, "#{@information[0]["title"]}-漳州房产资讯")
-provide(:key, "#{@information[0]["keywords"]}")
-provide(:desc, "#{@information[0]["description"]}")
.container
  .mb20.pull-left
    当前位置：
    = render_breadcrumbs
  .clearfix
.pull-left.content{style: "width:900px;"}
    .top
      .l
        %h1
          = @information[0]["title"]
        %p
          #{@information[0]["created_at"]}　来源: #{@information[0]["source"]} 点击量: #{@hit}
      .review
        %p
          = @information[0]["description"]
    .tj
      - Information.limit(4).each do |information|
        = link_to information.title, information, target: "_blank"
    .clearfix
    .news_body
      = @information[0]["content"].html_safe
    .same
      -if !@new_home.blank?
        .mb20{style: "border-bottom:1px  dotted #CCC"}
          %table.mb20
            %tr
              %td{width: "250px;"}
                = link_to image_tag(@new_home.new_home_thumb, alt: @new_home.name, :style => "height:150px; width:230px"), @new_home
              %td{width: "400px"}
                %h5.cl
                  [#{Area.find(@new_home.area_id).name}]
                  = link_to @new_home.name, @new_home, target: "_blank" , :class => "cl"
                  %span.label.label-important.ml10{style: "background:#f65c52"}
                    = Status.find(@new_home.status_id).name
                %p
                楼盘动态：
                -Information.where(["new_home_id = :home_id and category_id = :c_id",{ home_id: @new_home.id, c_id: 26 }]).limit(1).each do |information|
                  = link_to information.title.first(24), information, target: "_blank"
                %p 售楼电话：#{@new_home.tel}
                %p 项目地址：#{@new_home.project_address}

              %td{style: "text-align:center"}
                %h3.mt20.cr #{@new_home.price}元/m ²
                = link_to "团购报名",URI.unescape(new_home_path(@new_home.id,:type =>"index#tuangou")), :class => "btn btn-inverse ", :style => "background:#f65c52; color:#FFF",:target => "_blank"


      %h4.cr 相关阅读
      %ul
        - Information.where("category_id= ? and id != ?" ,@information[0]["category_id"] ,@information[0]["id"]).limit(6).each do |information|
          %li
            = link_to information.title.first(24), information, target: "_blank"
            = "..." if information.title.length >24
    .clearfix
    .bshare-custom.icon-medium-plus.ml20
      %a.bshare-qzone{title: "分享到QQ空间"}
      %a.bshare-sinaminiblog{title: "分享到新浪微博"}
      %a.bshare-weixin{title: "分享到微信"}
      %a.bshare-renren{title: "分享到人人网"}
      %a.bshare-qqmb{title: "分享到腾讯微博"}
      %a.bshare-neteasemb{title: "分享到网易微博"}
      %a.bshare-more.bshare-more-icon.more-style-addthis{title: "更多平台"}
    %script{charset: "utf-8", src: "http://static.bshare.cn/b/buttonLite.js#style=-1&uuid=&pophcol=2&lang=zh", type: "text/javascript"}
    %script{charset: "utf-8", src: "http://static.bshare.cn/b/bshareC0.js", type: "text/javascript"}

    / end fenxiang
  -# = render "right"